################################################################################################################################################################

# @project        Library ▸ Core
# @file           .travis.yml
# @author         Lucas Brémond <lucas@loftorbital.com>
# @license        Apache License 2.0

################################################################################################################################################################

branches:

    only:

        - /^\d+\.\d+(\.\d+)?(-\S*)?$/
        - master
        - dev

os:

    - linux

sudo: false

services:

    - docker

language: cpp

env:

    global:

        - LANG="en_US.UTF-8"

stages:

    - test
    - coverage
    - name: deploy
      if: tag =~ ^\d+\.\d+(\.\d+)?(-\S*)?$

jobs:

    include:

        - stage: test

          script:

                # Login to the Docker registry

                - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

                # Run tests

                - make test

        - stage: coverage

          script:

                # Login to the Docker registry

                - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

                # Run coverage

                - make coverage

        - stage: deploy

          script:

                # Login to the Docker registry

                - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

                # Generate and deploy documentation

                - make deploy-documentation

                # Generate binaries

                - make build-packages

          before_deploy:

                - echo "Deploying binaries to GitHub Releases..."

          deploy:

                - provider: releases
                  api_key: ${GITHUB_API_KEY}
                  file_glob: true
                  file:
                      - ./package/*
                  skip_cleanup: true
                  on:
                      branch: master
                      tags: true

                # - provider: pypi
                #   user: ${PYPI_USER}
                #   password: ${PYPI_PASSWORD}
                #   distributions: "bdist_wheel"
                #   skip_cleanup: true
                #   on:
                #       branch: master
                #       tags: true

          after_deploy:

                - echo "Deploying Python package to PyPI..."

                - make deploy-python

################################################################################################################################################################
